version: '3'
services:
  memcached:
    container_name: memcached
    image: "memcached:${MATRIX_MEMCACHED_VERSION}"
    entrypoint:
      - memcached
      - --enable-shutdown
      - --enable-sasl
    ports:
      - "11211:11211"
    restart: always
    networks:
      - ci
  memcached2:
    container_name: memcached2
    image: "memcached:${MATRIX_MEMCACHED_VERSION}"
    entrypoint:
      - memcached
      - --enable-shutdown
      - --port=11212
    ports:
      - "11212:11212"
    restart: always
    networks:
      - ci
  dalli:
    container_name: dalli
    build: .
    depends_on:
      - memcached
      - memcached2
    networks:
      - ci

networks:
  ci:
    name: ci
